### ISSUE TITLE
튜토리얼 페이지 퍼블리싱 수정

### ISSUE THREAD

**Issue by hyerinxx** [EFUB-GeumJaSsi/GiftU-Front#138]
## 1. 텍스트 색상 수정
나한테 필요한 건 바로 “에어팟” → gray/500 으로

<img width="300" alt="펀딩 소개하기" src="https://github.com/user-attachments/assets/dc4c2eee-35de-42e4-945c-4ac2ea631745">

## 2. 텍스트 내용 수정
가격대별 선물 보기 → 선물 상세 보기

<img width="300" alt="참여할 금액 입력하기" src="https://github.com/user-attachments/assets/8f2f976e-e3f7-4988-ab8e-29a2e35d2f34">

**Comment by sj0919** [comment]
해결 완료했습니다~
