### ISSUE TITLE
펀딩 상세 페이지 선물 후기 관련 건의

### ISSUE THREAD

**Issue by hyerinxx** [EFUB-GeumJaSsi/GiftU-Front#146]
## 1. 현안

펀딩 상세 페이지에서, 펀딩이 종료되었을 경우
- 개설자 화면에서 선물 후기 작성 버튼을 활성화한다.
- 기참여자 화면에서 개설자가 작성한 선물 후기를 보여준다.

## 2. 개선안

1. 펀딩 종료 & 선물 최저 금액보다 참여 금액이 큼 (펀딩 성공, 선물 받음)
   - 개설자 화면: 선물 후기 작성 버튼 O
   - 기참여자 화면: 개설자가 작성한 선물 후기 O

2. 펀딩 종료 & 선물 최저 금액보다 참여 금액이 작음 (펀딩 실패, 선물 못 받음)
   - 개설자 화면: 선물 후기 작성 버튼 X
   - 기참여자 화면: 개설자가 작성한 선물 후기 X

## 3. 기대 효과

- 선물을 못 받았는데 선물 후기를 작성해야 하는 불상사를 예방할 수 있음

**Comment by rwaeng** [comment]
이 부분 수정해서 배포한 거에도 반영되어 있는데 혹시 반영 안 된 화면 찾은 걸까요!?
![image](https://github.com/user-attachments/assets/653138ca-f801-4aec-a0f5-e17cd5f21dc1)

**Comment by hyerinxx** [comment]
앗!! 죄송합니다 제가 다른 화면을 보고 착각했어요 제가 만든 펀딩 중에 500원, 3만원 총 2개의 선물을 포함한 펀딩이 있었는데, 선물 금액이 너무 크게 차이 나서 500원 선물을 못 보고 3만원 선물만 포함한 펀딩으로 착각하고, 일부 금액만 모였는데도 선물 후기 관련 기능이 활성화된 줄 잘못 알았네요 죄송합니다🙇‍♂️ 이슈는 닫아 놓을게요!
